export const massiveOfEnglishWords = [
	['adult', 'взрослый'],
	['childhood', 'детство'],
	['maiden name', 'девичья фамилия'],
	['person', 'человек'],
	['personality', 'личность'],
	['surname', 'фамилия'],
	['teenager', 'подросток'],
	['youth', 'молодость'],
	['our', 'наш'],
	['arm', 'рука'],
	['back', 'спина'],
	['belly', 'живот'],
	['bone', 'кость'],
	['cheek', 'щека'],
	['chest', 'грудь'],
	['chin', 'подбородок'],
	['ear', 'ухо'],
	['elbow', 'локоть'],
	['eyebrow','бровь'],
	['eyelash','ресница'],
	['fist','кулак'],
	['foot','ступня'],
	['forehead','лоб'],
];
/*
	['eyebrow','бровь'],
	['eyelash','ресница'],
	['fist','кулак'],
	['foot','ступня'],
	['forehead','лоб'],
*/