export const massiveOfEnglishWords = [
	['adult', 'взрослый'],
	['childhood', 'детство'],
	['personality', 'личность'],
	['teenager', 'подросток'],
	['youth', 'молодость'],
	['back', 'спина'],
	['belly', 'живот'],
	['bone', 'кость'],
	['cheek', 'щека'],
	['chest', 'грудь'],
	['chin', 'подбородок'],
	['ear', 'ухо'],
	['elbow', 'локоть'],
	['eyebrow', 'бровь'],
	['eyelash', 'ресница'],
	['fist', 'кулак'],
	['foot', 'ступня'],
	['forehead', 'лоб'],
	['heel', 'пятка'],
	['hip', 'бедро'],
	['jaw', 'челюсть'],
	['kidney', 'почка'],
	['knee', 'колено'],
	['little finger', 'мизинец'],
	['liver', 'печень'],
	['lung', 'легкое'],
	['mouth', 'рот'],
	['nail', 'ноготь'],
	['neck', 'шея'],
	['nerve', 'нерв'],
];
/*
	['',''],
*/

/*
	['along','вдоль'],
	['around','вокруг'],
	['hand','кисть руки'],
	['our', 'наш'],
	['surname', 'фамилия'],
	['arm', 'рука'],
	['person', 'человек'],
	['maiden name', 'девичья фамилия'],
*/
